name:                functional-correctness-with-quickcheck
version:             0.1.0.0
github:              "HirotoShioi/functional-correctness-with-quickcheck"
license:             BSD3
author:              "Hiroto Shioi"
maintainer:          "shioihigg@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HirotoShioi/functional-correctness-with-quickcheck#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- mtl
- containers
- pretty-simple

library:
  source-dirs: src

executables:
  functional-correctness-with-quickcheck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-correctness-with-quickcheck

tests:
  functional-correctness-with-quickcheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-correctness-with-quickcheck
